version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: "1.12"
  ignore:
  - dependency-name: net.minecraftforge.gradle:ForgeGradle
    versions:
    - 4.0.13
    - 4.0.15
    - 4.0.16
    - 4.0.17
    - 4.0.18
    - 4.0.22
    - 4.0.23
    - 4.1.0
    - 4.1.1
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.1.7
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
