language : java
jdk:
- oraclejdk8
- openjdk8

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/d72f5dce347fdc1d218b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
- ./gradlew uploadCoverageToCodacy
